export default [
  {
    name: "Microsoft",
    date: "2021-08-31T22:10:29Z",
    designation: "Product Engineer",
    replies: 8,
    skills: "Security Awareness",
    location: "Carapicuíba",
    desc: "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",
  },
  {
    name: "Twitter",
    date: "2022-01-20T22:32:17Z",
    designation: "Engineer I",
    replies: 6,
    skills: "NPV",
    location: "Mahdalynivka",
    desc: "Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
  },
  {
    name: "Instagram",
    date: "2021-11-16T01:12:06Z",
    designation: "Pharmacist",
    replies: 3,
    skills: "Home Equity Lines of Credit",
    location: "Jos",
    desc: "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
  },
  {
    name: "Twitch",
    date: "2022-04-07T15:32:54Z",
    designation: "Nuclear Power Engineer",
    replies: 8,
    skills: "DFSORT",
    location: "Dakoro",
    desc: "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
  },
  {
    name: "Gitlab",
    date: "2021-12-13T03:40:50Z",
    designation: "Adjustment Coordinator",
    replies: 10,
    skills: "Pneumatic Conveying",
    location: "Purworejo",
    desc: "Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.",
  },
  {
    name: "Github",
    date: "2021-11-26T02:04:54Z",
    designation: "Statistician I",
    replies: 5,
    skills: "Yellow Book",
    location: "Poitiers",
    desc: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.",
  },
  {
    name: "Amazon",
    date: "2022-02-10T19:42:35Z",
    designation: "Chemical Engineer",
    replies: 4,
    skills: "LDPE",
    location: "Opočno",
    desc: "In hac habitasse platea dictumst.In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.",
  },
  {
    name: "Apple",
    date: "2022-06-10T11:27:09Z",
    designation: "Safety Technician I",
    replies: 5,
    skills: "Observational Astronomy",
    location: "Choloma",
    desc: "In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.",
  },
  {
    name: "Google",
    date: "2022-01-28T19:25:42Z",
    designation: "Actuary",
    replies: 10,
    skills: "FPA",
    location: "Pak Phayun",
    desc: "Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
  },
  {
    name: "Spotify",
    date: "2022-07-04T07:40:41Z",
    designation: "Design Engineer",
    replies: 6,
    skills: "Health Education",
    location: "Xiaohenglong",
    desc: "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
  },
];
